### ISSUE TITLE
기본 레이아웃

### ISSUE THREAD

**Issue by rhiokim** [planarialab/gona-for-web#1]
* [x] 좌측 타임 트래킹 (내일, 오늘, 어제 3가지 항목만)
* [x] 할일 목록 (최대 5개의 항목만)
* [ ] ~~사용자 프로필 (닉네임 정도만 표시되도록 영역)~~
* [ ] ~~진행상황 상태 영역 ( 영역만 잡고 마크업은 향후 진행)~~

**Comment by rhiokim** [comment]
`~/tasks` 로 접근하면 일단 마크업.. bootstrap 으로 변경할까 고민중이에요.
일단 룩앤필은 중요하지 않으니 현재 상태로 완료처리합니다.

**Comment by J2P** [comment]
이 이슈는 닫아도 되지 않을까요?
